### ISSUE TITLE
dependency to openssl1 fails at recent ubuntu

### ISSUE THREAD

**Issue by jose-d** [MrCarroll/root-snap#3]
If I understood snap [build procedure](https://github.com/MrCarroll/root-snap/blob/main/.github/workflows/build.yaml) correctly, root-snap is being built at `ubuntu-latest`  image.

`ubuntu-latest` is at this moment quite old - [github actions docu](https://github.com/actions/runner-images) says, it's ubuntu 20.04 containing openssl1xx.

[Since ubuntu 22.04](https://discourse.ubuntu.com/t/openssl-3-0-transition-plans/24453), there is openssl3, and this causes missing libssl dependencies - eg:

```
jose@jose-t14s:/snap/root-framework/880$ pwd
/snap/root-framework/880
jose@jose-t14s:/snap/root-framework/880$ ldd ./usr/local/lib/libNet.so
        linux-vdso.so.1 (0x00007ffc51dc1000)
        libRIO.so => /snap/root-framework/880/./usr/local/lib/libRIO.so (0x00007f76fc29e000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libCore.so => /snap/root-framework/880/./usr/local/lib/libCore.so (0x00007f76fbbf9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f76fbbf4000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f76fb800000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76fbbd2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76fb400000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f76fbbcd000)
        libThread.so => /snap/root-framework/880/./usr/local/lib/libThread.so (0x00007f76fbb3a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76fba51000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f76fc929000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f76fb78a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f76fb75f000)
        libxxhash.so.0 => /lib/x86_64-linux-gnu/libxxhash.so.0 (0x00007f76fba3a000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f76fb73f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f76fb723000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f76fb674000)
jose@jose-t14s:/snap/root-framework/880$
```

This causes build failures for certain user-written utilities at our research center.
Workaround was to use binary tarball distributed by CERN, but it would be nice to have working snap with recent Ubuntu too.

**Comment by MrCarroll** [comment]
Hello,

It sounds like you might be accessing the snaps content directly from the host; the snap should run fine on 22.04 when inside it's own runtime environment, which bundles OpenSSL 1.1. You can test that directly by trying:
```
snap run --shell root-framework
ldd /snap/root-framework/current/usr/local/lib/libNet.so
```

This means I'd expect it to work for the basics on any distribution including 22.04 when being accessed as either `root` (assuming `which root` points to `/snap`) or explicitly via `snap run root-framework`.

Unfortunately, if you're relying on the differing behaviour of accessing the snap directly, this can't be guaranteed and is effectively an unsupportable usecase, if it were to be rebuilt from 22.04, people on 20.04 would now suddenly find it broken instead. The CERN provided binaries, and Conda release, are more suitable for these scenarios.

Can you confirm how the snaps being used in your usecase? If you need to do some minimal manipulation with `gcc` and `cmake` for example, you can try using `root-framework.cmake` and executing any generating binaries with `root-framework.run $binaryName`. For simple projects, this might happen to work completely fine, but begins to show its warts the second dependencies are involved that aren't shipped with the snap. There might be some change I can do to accomodate the snap better, but it may also be the case that it's not a suitable fit in this scenario.

Finally, the snap will probably be rebuilt for 22.04 in the next release of ROOT; but it sounds like you might continue to hit into this problem with other distributions even when it does.

**Comment by jose-d** [comment]
Hello! Thanks for detailed reply and explanation.

Apparently the problem was in my wrong understanding how organization of '*.so' files works in snap directory/mount structure and it is not bug in your build recipe.

It seems that snap is not the right tool for our usecase.

I'm closing this issue.

cheers

**Comment by MrCarroll** [comment]
Hey,

You might be interested in the following Apt package of ROOT for Ubuntu 22.04;

https://root-forum.cern.ch/t/unofficial-root-6-26-10-package-for-ubuntu-22-04/52773

As a native installation for Ubuntu 22.04 you might find that it works much better for your needs, as it should install at a system level rather than being isolated as the snap is.
